PROGRAM exams_grade

 IMPLICIT NONE
  INTEGER :: i
  REAL, DIMENSION(10)::R     !R=RESULTS OF STUDENTS
  CHARACTER(LEN=15)::A,B,C,F,DISTINCTION,CREDIT, PASS, FAIL
 INTEGER,DIMENSION(10) :: scores=(/85,62,45,91,38,74,55,88,61,47/)
 PRINT*,'PLEASE ENTER 10 RESULTS'
  
   DO i=1,10
    READ*, R(i)
   END DO
   
 DO i=1,10
   
   IF ((R(i)>=80.00).AND.(R(i)<=100.00)) THEN
    PRINT*,'A',R(i), '  ','DISTINCTION'
   ELSE IF ((R(i)>=60.00).AND.(R(i)<=79.00)) THEN
    PRINT*,'B',R(i),'  ','CREDIT'
   ELSE IF ((R(i)>=40.00).AND.(R(i)<=59.00)) THEN
    PRINT*,'C',R(i),'  ','PASS'
   ELSE IF ((R(i)>=0.00).AND.(R(i)<=39.99)) THEN
    PRINT*,'F',R(i),'  ','FAIL'
   ELSE 
    PRINT*,'ERROR:  INVALID MARKS' 
   END IF
   
  END DO   
  
END PROGRAM exams_grade
         !AMPONSAH STEPHEN TETTEH-6306824
